require("dotenv").config();
const mongoose = require("mongoose");
const Instrument = require("../models/Instrument");

const instruments = [
  {
    instrument_id: "mutual-fund-equity-large-cap",
    name: "Equity Mutual Fund — Large Cap",
    description: "A large-cap equity mutual fund pools money from multiple investors and invests at least 80% in the top 100 companies by market capitalisation on NSE/BSE, as mandated by SEBI. Managed by professional fund managers, it offers broad diversification across India's biggest blue-chip companies without requiring individual stock research. Returns are fully market-linked — no guaranteed floor. LTCG above ₹1.25 lakh taxed at 12.5%; STCG at 20%. Best suited for long-term wealth creation with lower volatility than mid/small-cap funds.",
    instrument_type: "mutual_fund_equity",
    asset_class: "equity",
    return_nature: "market_linked",
    indicative_return_min_pct_pa: null,
    indicative_return_max_pct_pa: null,
    risk_level: "high",
    capital_protection: "none",
    liquidity_level: "t2_t3",
    lock_in_years: null,
    typical_cost_pct_pa: 0.8,
    tax_treatment: "TET",
    suitable_for_80c: false,
    tax_deduction_section: null,
    recommended_horizon: "long",
    inflation_beat_potential: "high",
    goal_tags: ["wealth_creation", "inflation_hedge"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "SEBI mandates minimum 80% allocation to large-cap stocks (ranked 1–100 by market cap) — reduces manager discretion",
      "Direct plan expense ratio: 0.5–1.0%; regular plan: 1.5–2.0% — always prefer direct for long-term investment",
      "LTCG above ₹1.25 lakh taxed at 12.5% (no indexation); STCG taxed at 20% — effective from 23 July 2024",
      "Open-ended with no lock-in — redemption proceeds credited in 2–3 business days (T+2/T+3)",
      "Large-cap funds historically less volatile than mid/small-cap but more predictable in downturns",
    ],
  },
  {
    instrument_id: "mutual-fund-liquid",
    name: "Liquid Mutual Fund",
    description: "A liquid mutual fund invests exclusively in very short-term money market instruments (treasury bills, commercial paper, certificates of deposit) with maturities up to 91 days. It is the safest mutual fund category — designed as a cash management tool, a smarter alternative to a savings bank account for idle funds. Instant redemption of up to ₹50,000 is available 24x7; larger amounts settle in 1 business day. Returns are relatively stable at 6.5–7.5% p.a. but are not guaranteed. Post-Budget 2023, gains are taxed at slab rate regardless of holding period.",
    instrument_type: "mutual_fund_debt",
    asset_class: "debt",
    return_nature: "market_linked",
    indicative_return_min_pct_pa: 6.5,
    indicative_return_max_pct_pa: 7.5,
    risk_level: "low",
    capital_protection: "none",
    liquidity_level: "instant",
    lock_in_years: null,
    typical_cost_pct_pa: 0.2,
    tax_treatment: "complex",
    suitable_for_80c: false,
    tax_deduction_section: null,
    recommended_horizon: "short",
    inflation_beat_potential: "low",
    goal_tags: ["emergency_fund", "short_term_parking"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "Invests only in instruments with residual maturity up to 91 days — minimum interest rate risk in the mutual fund universe",
      "Instant redemption of up to ₹50,000 (or 90% of portfolio) available 24x7 including weekends and public holidays",
      "No exit load after 7 days; graded exit load in first 7 days on most funds (discourages very short holding)",
      "Budget 2023 removed LTCG benefit for debt mutual funds — gains taxed at slab rate regardless of holding period",
      "Typically earns 0.5–1.0% more than savings bank account with comparable safety and better liquidity",
    ],
  },
  {
    instrument_id: "tax-saver-fd",
    name: "Tax-Saver Fixed Deposit (5-Year)",
    description: "A Tax-Saver Fixed Deposit is a 5-year bank FD that qualifies for Section 80C tax deductions up to ₹1.5 lakh per year under the old tax regime. Unlike regular FDs, it has a mandatory 5-year lock-in with no premature withdrawal or loan-against-FD allowed. Interest rates typically range from 6.5–7.25% p.a. and are taxed at the investor's applicable slab rate every year, even though the principal investment gets an 80C deduction. DICGC insures up to ₹5 lakh per depositor per bank. Best for conservative 80C investors who want guaranteed returns with no market risk.",
    instrument_type: "bank_deposit",
    asset_class: "debt",
    return_nature: "fixed",
    indicative_return_min_pct_pa: 6.5,
    indicative_return_max_pct_pa: 7.25,
    risk_level: "low",
    capital_protection: "partial_insured",
    liquidity_level: "locked",
    lock_in_years: 5,
    typical_cost_pct_pa: 0,
    tax_treatment: "complex",
    suitable_for_80c: true,
    tax_deduction_section: "80C",
    recommended_horizon: "medium",
    inflation_beat_potential: "low",
    goal_tags: ["tax_saving_80c", "short_term_parking"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "80C deduction available only under old tax regime — not applicable if investor has opted for new regime",
      "Strictly no premature withdrawal, no loan against FD, and no sweep facility during the 5-year lock-in",
      "Interest earned is taxable at slab rate every year — TDS deducted at 10% if annual interest exceeds ₹40,000",
      "Senior citizens typically earn 0.25–0.50% extra — 80C benefit stacks with the senior citizen rate advantage",
      "DICGC insurance covers up to ₹5 lakh (principal + interest combined) per depositor per bank",
      "Different banks offer different rates — compare before choosing; small finance banks often offer 50–75 bps higher",
    ],
  },
  {
    instrument_id: "nps-tier1-e",
    name: "NPS Tier I — Equity (E)",
    description: "NPS Tier I Equity Scheme (E) is the highest-risk, highest-return option within the National Pension System — India's government-backed voluntary retirement savings scheme. It invests in equity markets via SEBI-regulated pension fund managers at an ultra-low fund management charge of approximately 0.09%. The account is locked until age 60; at maturity, 60% of the corpus can be withdrawn tax-free as a lump sum, while 40% must be used to purchase an annuity (monthly pension), which is taxable as income. An additional ₹50,000 deduction under Section 80CCD(1B) is available beyond the ₹1.5L 80C limit.",
    instrument_type: "pension",
    asset_class: "equity",
    return_nature: "market_linked",
    indicative_return_min_pct_pa: null,
    indicative_return_max_pct_pa: null,
    risk_level: "high",
    capital_protection: "none",
    liquidity_level: "locked",
    lock_in_years: null,
    typical_cost_pct_pa: 0.09,
    tax_treatment: "complex",
    suitable_for_80c: true,
    tax_deduction_section: "80CCD(1B)",
    recommended_horizon: "very_long",
    inflation_beat_potential: "high",
    goal_tags: ["retirement", "tax_saving_80c"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "Lowest fund management charge in any equity investment in India — approximately 0.09% p.a. (vs 0.5–1.5% for mutual funds)",
      "Extra ₹50,000 deduction under Section 80CCD(1B) — exclusive to NPS, over and above the ₹1.5L 80C limit",
      "60% of corpus at maturity (age 60) is fully tax-free; 40% must purchase annuity — annuity income taxed at slab",
      "Equity allocation capped at 75% (Active Choice); reduces automatically to 50% at age 50 under Auto LC50 lifecycle",
      "Premature exit allowed after 3 years — but 80% must buy annuity; only 20% withdrawable as lump sum",
      "Partial withdrawal (up to 25% of own contributions) allowed after 3 years for specific reasons: education, marriage, medical, home",
    ],
  },
  {
    instrument_id: "nps-tier1-c",
    name: "NPS Tier I — Corporate Bond (C)",
    description: "NPS Tier I Corporate Bond Scheme (C) invests in fixed-income instruments — corporate bonds, debentures, and money market instruments rated AA and above. It offers stable, moderate returns compared to the Equity (E) scheme, making it suitable for conservative NPS subscribers or those closer to retirement who want to reduce equity exposure. Like all NPS Tier I accounts, funds are locked until age 60 with the same 60:40 withdrawal-to-annuity rule at maturity. Ultra-low fund management charges at ~0.09% significantly outperform equivalent debt mutual funds on cost.",
    instrument_type: "pension",
    asset_class: "debt",
    return_nature: "market_linked",
    indicative_return_min_pct_pa: null,
    indicative_return_max_pct_pa: null,
    risk_level: "low_to_moderate",
    capital_protection: "none",
    liquidity_level: "locked",
    lock_in_years: null,
    typical_cost_pct_pa: 0.09,
    tax_treatment: "complex",
    suitable_for_80c: true,
    tax_deduction_section: "80CCD(1B)",
    recommended_horizon: "very_long",
    inflation_beat_potential: "moderate",
    goal_tags: ["retirement", "tax_saving_80c"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "Invests in AA-rated and above corporate bonds — credit risk is low but not zero unlike G scheme",
      "Fund management charge approximately 0.09% — far lower than equivalent corporate bond mutual funds",
      "Same tax rules as NPS Equity scheme: 60% tax-free lump sum at 60, 40% compulsory annuity purchase",
      "Under Active NPS choice, investor can allocate up to 100% to C scheme (no equity cap applies)",
      "NPS Scheme C historically returned 9–11% p.a. — better than most bank FDs over 10-year periods",
    ],
  },
  {
    instrument_id: "nps-tier1-g",
    name: "NPS Tier I — Government Bond (G)",
    description: "NPS Tier I Government Bond Scheme (G) is the safest option within NPS — investing exclusively in central and state government securities (G-Secs). Returns track prevailing government bond yields, offering low but stable returns with virtually zero credit risk. Suitable for the most risk-averse NPS subscribers who prioritise capital safety within a pension wrapper. Like all NPS Tier I accounts, funds are locked until age 60 with the same 60% tax-free withdrawal and 40% compulsory annuity rule at maturity.",
    instrument_type: "pension",
    asset_class: "debt",
    return_nature: "market_linked",
    indicative_return_min_pct_pa: null,
    indicative_return_max_pct_pa: null,
    risk_level: "low",
    capital_protection: "none",
    liquidity_level: "locked",
    lock_in_years: null,
    typical_cost_pct_pa: 0.09,
    tax_treatment: "complex",
    suitable_for_80c: true,
    tax_deduction_section: "80CCD(1B)",
    recommended_horizon: "very_long",
    inflation_beat_potential: "low",
    goal_tags: ["retirement", "tax_saving_80c"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "Invests only in central and state government securities — zero credit risk (sovereign guarantee)",
      "Returns sensitive to interest rate movements — NAV falls when rates rise (interest rate risk remains even in G scheme)",
      "Fund management charge approximately 0.09% — lowest cost fixed-income retirement product in India",
      "Suitable for investors aged 55+ who want to de-risk NPS portfolio as they approach retirement",
      "NPS Scheme G historically returned 8–10% p.a. — comparable to PPF but with market-linked NAV fluctuation",
    ],
  },
  {
    instrument_id: "listed-equity-stock",
    name: "Listed Equity Shares",
    description: "Listed equity shares are ownership stakes in publicly traded companies on NSE or BSE. Unlike mutual funds, direct stock investing puts full responsibility for research, stock selection, and timing on the investor — there is no fund manager. Returns are entirely market-linked with no floor. Requires a demat account and active monitoring. India moved to T+1 settlement — shares and proceeds move the next trading day. LTCG above ₹1.25 lakh taxed at 12.5%; STCG at 20%. Highest potential returns among all instruments, but also the highest skill and attention requirement.",
    instrument_type: "stock",
    asset_class: "equity",
    return_nature: "market_linked",
    indicative_return_min_pct_pa: null,
    indicative_return_max_pct_pa: null,
    risk_level: "very_high",
    capital_protection: "none",
    liquidity_level: "t1",
    lock_in_years: null,
    typical_cost_pct_pa: 0.1,
    tax_treatment: "TET",
    suitable_for_80c: false,
    tax_deduction_section: null,
    recommended_horizon: "long",
    inflation_beat_potential: "high",
    goal_tags: ["wealth_creation", "inflation_hedge"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "T+1 settlement — shares credited to demat or sale proceeds credited to bank account the next trading day",
      "LTCG above ₹1.25 lakh taxed at 12.5% (no indexation); STCG at 20% — effective from 23 July 2024",
      "STT (Securities Transaction Tax) of 0.1% applies on both buy and sell for delivery trades",
      "Dividends received are taxable at the investor's applicable slab rate — TDS at 10% if dividends exceed ₹5,000/year",
      "No upper investment limit; fractional shares NOT available in India (unlike US markets)",
      "Requires demat account + trading account + linked bank account — typically bundled as a 3-in-1 account",
    ],
  },
  {
    instrument_id: "g-sec",
    name: "Government Securities — G-Sec / T-Bill",
    description: "Government Securities (G-Secs) and Treasury Bills (T-Bills) are debt instruments issued by the Government of India to borrow from the public market. T-Bills are short-term (91, 182, or 364 days) zero-coupon instruments issued at a discount to face value. G-Secs are long-term bonds (5–40 year maturity) paying a fixed semi-annual coupon. Both carry zero credit risk — they are backed by sovereign guarantee. Retail investors can now buy directly via the RBI Retail Direct platform (rbiretaildirect.org.in) with no broker or intermediary needed.",
    instrument_type: "bond_govt",
    asset_class: "debt",
    return_nature: "fixed",
    indicative_return_min_pct_pa: 6.8,
    indicative_return_max_pct_pa: 7.4,
    risk_level: "low",
    capital_protection: "full",
    liquidity_level: "low",
    lock_in_years: null,
    typical_cost_pct_pa: 0,
    tax_treatment: "complex",
    suitable_for_80c: false,
    tax_deduction_section: null,
    recommended_horizon: "medium",
    inflation_beat_potential: "low",
    goal_tags: ["regular_income", "short_term_parking"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "Available directly to retail investors via RBI Retail Direct portal — no broker, no demat charges, no commissions",
      "Zero credit risk — Government of India sovereign guarantee on principal and coupon payments",
      "Price moves inversely to interest rates — selling G-Sec before maturity can result in gains or capital losses",
      "Coupon income taxed at applicable slab rate; LTCG on secondary market sale at 10% without indexation (holding >3 years)",
      "T-Bills: 91/182/364-day maturities; issued at discount, redeemed at face value — return is the discount, not coupon",
      "Minimum investment ₹10,000 (face value) via RBI Retail Direct; can be held to maturity with zero secondary market concern",
    ],
  },
  {
    instrument_id: "corporate-bond-ncd",
    name: "Corporate Bond — Listed NCD",
    description: "Listed Non-Convertible Debentures (NCDs) are fixed-income instruments issued by companies to raise debt from the public at a fixed interest rate (coupon). They offer higher rates than government bonds or FDs to compensate for credit risk — the risk that the company may default. NCDs are rated by agencies like CRISIL and ICRA; AAA-rated NCDs from top companies are relatively safe, while lower-rated NCDs carry higher default risk and higher yield. Listed on BSE/NSE for secondary trading, though liquidity is typically very thin. Suitable for investors seeking regular income above FD rates.",
    instrument_type: "bond_corporate",
    asset_class: "debt",
    return_nature: "fixed",
    indicative_return_min_pct_pa: 8.0,
    indicative_return_max_pct_pa: 11.0,
    risk_level: "moderate",
    capital_protection: "none",
    liquidity_level: "low",
    lock_in_years: null,
    typical_cost_pct_pa: 0,
    tax_treatment: "complex",
    suitable_for_80c: false,
    tax_deduction_section: null,
    recommended_horizon: "medium",
    inflation_beat_potential: "moderate",
    goal_tags: ["regular_income"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "Coupon rate is credit-risk-adjusted — AAA: 8–9%, AA: 9–10%, A and below: 10%+ (higher yield = higher default risk)",
      "Interest income taxed at applicable slab rate; capital gains on secondary market sale follow STCG/LTCG rules",
      "Listed on BSE/NSE but secondary market liquidity is typically very thin — plan to hold to maturity",
      "In default, NCD holders rank above equity shareholders but may rank below secured creditors depending on NCD structure",
      "SEBI mandates a registered Debenture Trustee to act on behalf of NCD holders in case of default or covenant breach",
      "Minimum investment typically ₹10,000 (face value); available in public issue (primary market) or on exchange (secondary)",
    ],
  },
  {
    instrument_id: "reit",
    name: "REIT — Real Estate Investment Trust",
    description: "A Real Estate Investment Trust (REIT) lets retail investors earn from income-generating commercial real estate — office parks, retail malls, and warehouses — without directly buying property. REITs own, operate, and manage a portfolio of properties and must distribute at least 90% of their net distributable cash flow to unit holders every quarter. Listed on NSE/BSE with T+1 settlement, they combine the liquidity of stocks with the income characteristics of real estate. Three major REITs exist in India: Embassy REIT, Mindspace REIT, and Nexus Select Trust.",
    instrument_type: "reit",
    asset_class: "real_estate",
    return_nature: "market_linked",
    indicative_return_min_pct_pa: null,
    indicative_return_max_pct_pa: null,
    risk_level: "moderately_high",
    capital_protection: "none",
    liquidity_level: "t1",
    lock_in_years: null,
    typical_cost_pct_pa: 0.5,
    tax_treatment: "complex",
    suitable_for_80c: false,
    tax_deduction_section: null,
    recommended_horizon: "long",
    inflation_beat_potential: "moderate",
    goal_tags: ["regular_income", "real_estate_exposure", "inflation_hedge"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "Must distribute at least 90% of Net Distributable Cash Flow (NDCF) to unit holders every quarter — predictable income",
      "Distributions have 3 tax components: interest (taxed at slab), dividend (exempt), principal repayment (return of capital)",
      "SEBI mandates at least 80% of REIT assets in completed, revenue-generating properties — limits development risk",
      "Listed on NSE/BSE with T+1 settlement — far more liquid than direct real estate ownership",
      "Minimum investment approximately ₹10,000–15,000 per lot — accessible vs crores for direct commercial property",
      "LTCG on unit sale after 3 years taxed at 10%; STCG before 3 years taxed at 15% (equity-like treatment for listed REITs)",
    ],
  },
  {
    instrument_id: "invit",
    name: "InvIT — Infrastructure Investment Trust",
    description: "An Infrastructure Investment Trust (InvIT) is similar to a REIT but for infrastructure assets — toll roads, power transmission lines, gas pipelines, and renewable energy plants. InvITs allow retail investors to earn steady, inflation-linked cash flows from essential infrastructure projects. They are listed on NSE/BSE and must distribute at least 90% of their net distributable cash flow quarterly. Infrastructure assets generate revenues through long-term concession agreements (tolls, transmission fees) with built-in annual escalation clauses, providing a natural inflation hedge.",
    instrument_type: "invit",
    asset_class: "infrastructure",
    return_nature: "market_linked",
    indicative_return_min_pct_pa: null,
    indicative_return_max_pct_pa: null,
    risk_level: "moderately_high",
    capital_protection: "none",
    liquidity_level: "t1",
    lock_in_years: null,
    typical_cost_pct_pa: 0.5,
    tax_treatment: "complex",
    suitable_for_80c: false,
    tax_deduction_section: null,
    recommended_horizon: "long",
    inflation_beat_potential: "moderate",
    goal_tags: ["regular_income", "inflation_hedge"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "Must distribute at least 90% of Net Distributable Cash Flow quarterly — regular income like REITs",
      "Infrastructure assets generate inflation-linked revenues — toll roads typically have 3–5% annual traffic/tariff escalation",
      "Major listed InvITs: IRB InvIT, India Grid Trust, PowerGrid InvIT, Highways Infrastructure Trust, Bharat Highways InvIT",
      "Distribution tax components: interest (slab rate), dividend (exempt), principal repayment (return of capital) — complex tax treatment",
      "Infrastructure projects operate under long-term government concession agreements — revenue visibility over 20–30 years",
      "Minimum investment approximately ₹5,000–10,000 per lot; lower than REIT due to different pricing",
    ],
  },
  {
    instrument_id: "p2p-lending",
    name: "P2P Lending",
    description: "Peer-to-Peer (P2P) lending platforms connect individual lenders directly with borrowers, bypassing traditional banks. Lenders earn interest rates of 10–18% p.a. by funding personal loans across multiple borrowers. Regulated by RBI as NBFC-P2P, platforms maintain escrow accounts and enforce a ₹50 lakh per-lender cap. The primary risk is borrower default — there is no DICGC insurance or government guarantee on lender capital. Diversifying across 200+ borrowers is the key risk management strategy. Gross returns of 10–18% typically translate to net 8–13% after factoring in defaults.",
    instrument_type: "p2p",
    asset_class: "alternative",
    return_nature: "fixed",
    indicative_return_min_pct_pa: 10.0,
    indicative_return_max_pct_pa: 18.0,
    risk_level: "very_high",
    capital_protection: "none",
    liquidity_level: "very_low",
    lock_in_years: null,
    typical_cost_pct_pa: 1.0,
    tax_treatment: "complex",
    suitable_for_80c: false,
    tax_deduction_section: null,
    recommended_horizon: "medium",
    inflation_beat_potential: "high",
    goal_tags: ["regular_income", "wealth_creation"],
    ideal_age_min: 18,
    ideal_age_max: null,
    special_features: [
      "RBI regulates P2P platforms as NBFC-P2P — must obtain RBI certificate of registration; check before investing",
      "Maximum investment capped at ₹50 lakh per lender across ALL P2P platforms combined (RBI regulation, 2024)",
      "Diversify across 200+ borrowers minimum — single default impact drops below 0.5% on well-diversified portfolio",
      "Interest income taxed at applicable slab rate; default losses are NOT tax-deductible as capital losses",
      "No secondary market for most P2P loans — money locked until borrower repays (typically 12–36 month tenure)",
      "Gross returns of 10–18% reduce to 8–13% net after defaults — evaluate platform-disclosed historical default rates carefully",
    ],
  },
  {
    instrument_id: "scss",
    name: "SCSS — Senior Citizens Savings Scheme",
    description: "The Senior Citizens Savings Scheme (SCSS) is a government-backed savings instrument exclusively for Indian citizens aged 60 and above (or 55+ for VRS/superannuation retirees). It offers one of the highest guaranteed fixed returns among government schemes at 8.2% per annum, paid quarterly directly to the investor's bank account — ideal for post-retirement regular income. The 5-year tenure is extendable by 3 years. Investment qualifies for Section 80C deduction, and both principal and interest are backed by Government of India sovereign guarantee.",
    instrument_type: "government_scheme",
    asset_class: "debt",
    return_nature: "fixed",
    indicative_return_min_pct_pa: 8.2,
    indicative_return_max_pct_pa: 8.2,
    risk_level: "low",
    capital_protection: "full",
    liquidity_level: "low",
    lock_in_years: 5,
    typical_cost_pct_pa: 0,
    tax_treatment: "complex",
    suitable_for_80c: true,
    tax_deduction_section: "80C",
    recommended_horizon: "medium",
    inflation_beat_potential: "low",
    goal_tags: ["regular_income", "tax_saving_80c"],
    ideal_age_min: 60,
    ideal_age_max: null,
    special_features: [
      "Exclusive to citizens aged 60+ (or 55+ for VRS/superannuation retirees; defence personnel from 50+)",
      "Maximum investment raised to ₹30 lakh per individual (Union Budget 2023 — doubled from earlier ₹15L limit)",
      "Interest paid quarterly directly to bank account — one of the best regular income instruments for retirees",
      "TDS deducted at 10% if quarterly interest exceeds ₹50,000/year; submit Form 15H if total income is below taxable limit",
      "Premature closure allowed after 1 year with penalty: 1.5% deduction (Year 1–2), 1% deduction (after Year 2)",
      "5-year tenure extendable once by 3 years — submit extension request within 1 year of maturity date",
    ],
  },
  {
    instrument_id: "sukanya-samriddhi-yojana",
    name: "Sukanya Samriddhi Yojana",
    description: "Sukanya Samriddhi Yojana (SSY) is a government savings scheme for the girl child, launched under the Beti Bachao Beti Padhao initiative. A parent or legal guardian can open an account for a girl child below 10 years of age. It offers EEE tax status — investment, interest earned, and maturity proceeds are all fully tax-free — combined with one of the highest government-backed returns at 8.2% per annum. The account matures when the girl turns 21, with partial withdrawal allowed at 18 for higher education or marriage. Maximum two accounts per family (one per girl child).",
    instrument_type: "government_scheme",
    asset_class: "debt",
    return_nature: "fixed",
    indicative_return_min_pct_pa: 8.2,
    indicative_return_max_pct_pa: 8.2,
    risk_level: "low",
    capital_protection: "full",
    liquidity_level: "locked",
    lock_in_years: 21,
    typical_cost_pct_pa: 0,
    tax_treatment: "EEE",
    suitable_for_80c: true,
    tax_deduction_section: "80C",
    recommended_horizon: "very_long",
    inflation_beat_potential: "low",
    goal_tags: ["child_education", "tax_saving_80c"],
    ideal_age_min: 0,
    ideal_age_max: 10,
    special_features: [
      "Account must be opened before girl child turns 10 years — maximum 2 accounts per family (1 per girl child)",
      "EEE tax status — investment (80C deduction), annual interest earned, and full maturity amount are all tax-free",
      "Deposits must be made for only 15 years even though account matures at age 21 — grows tax-free for remaining 6 years",
      "Partial withdrawal up to 50% of previous year's balance allowed when girl turns 18 (for education or marriage)",
      "Minimum annual deposit ₹250; maximum ₹1.5 lakh — same ceiling as overall 80C limit",
      "Account becomes dormant if minimum ₹250 not deposited in a year; reactivate by paying ₹50 penalty per dormant year",
    ],
  },
];

async function run() {
  await mongoose.connect(process.env.MONGODB_URL || "mongodb://localhost:27017/clarifin");
  console.log("Connected to MongoDB\n");

  let seeded = 0;
  let skipped = 0;

  for (const data of instruments) {
    const exists = await Instrument.findOne({ instrument_id: data.instrument_id });
    if (exists) {
      console.log(`  ⟳  Already exists: ${data.instrument_id}`);
      skipped++;
      continue;
    }
    await Instrument.create(data);
    console.log(`  ✓  Seeded: ${data.instrument_id}`);
    seeded++;
  }

  console.log(`\nDone — ${seeded} seeded, ${skipped} skipped.`);
  await mongoose.disconnect();
}

run().catch(err => { console.error(err); process.exit(1); });
