/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_models/diamond.glb -o src/components/DiamondModel.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, MeshTransmissionMaterial, Center } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
}

export function DiamondModel(props: React.JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/3d_models/diamond_fixed.glb') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      {/* Hologram Projection Base */}
      <group position={[0, -1, 0]}>
        {/* Glowing Rings */}
        <mesh rotation={[-Math.PI / 2, 0, 0]}>
          <ringGeometry args={[2.5, 3.0, 64]} />
          <meshBasicMaterial color="#8B5CF6" transparent opacity={0.8} blending={THREE.AdditiveBlending} depthWrite={false} />
        </mesh>
        <mesh rotation={[-Math.PI / 2, 0, 0]}>
          <ringGeometry args={[3.2, 3.4, 64]} />
          <meshBasicMaterial color="#8B5CF6" transparent opacity={0.4} blending={THREE.AdditiveBlending} depthWrite={false} />
        </mesh>
        {/* Soft core glow */}
        <mesh rotation={[-Math.PI / 2, 0, 0]}>
          <circleGeometry args={[2.5, 64]} />
          <meshBasicMaterial color="#8B5CF6" transparent opacity={0.2} blending={THREE.AdditiveBlending} depthWrite={false} />
        </mesh>
        
        {/* Hologram Light Beams (Shooting Upwards) */}
        <mesh position={[0, 1.5, 0]}>
          <cylinderGeometry args={[3.0, 3.0, 3.0, 32, 1, true]} />
          <meshBasicMaterial color="#8B5CF6" transparent opacity={0.08} blending={THREE.AdditiveBlending} depthWrite={false} side={THREE.DoubleSide} />
        </mesh>
      </group>

      <Center position={[0, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} rotation={[-Math.PI / 2, 0, 0]}>
          <MeshTransmissionMaterial 
            color="#C084FC"
            attenuationColor="#FFFFFF"
            attenuationDistance={10}
            transparent={true}
            opacity={0.5}
            backside={true}
            backsideThickness={1}
            samples={6}
            thickness={2}
            chromaticAberration={0.1}
            anisotropy={0.1}
            ior={2.4}
            transmission={0.7}
            roughness={0.05}
            metalness={0.1}
            clearcoat={1}
            clearcoatRoughness={0}
            envMapIntensity={2}
            resolution={512}
          />
        </mesh>
      </Center>
    </group>
  )
}

useGLTF.preload('/3d_models/diamond_fixed.glb')
