/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_models/maze.glb -o src/components/MazeModel.tsx -t 
Author: PropShop™ (https://sketchfab.com/syedabbas0815)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/maze-9d19583569ec4a5fbaa6a735793fdb1b
Title: Maze
*/

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Maze_Material_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: any[]
}

import { useScroll, useTransform, MotionValue } from 'framer-motion'

type MazeProps = React.JSX.IntrinsicElements['group'] & {
  scrollProgress?: MotionValue<number>
}

export function Model({ scrollProgress, ...props }: MazeProps) {
  const { nodes, materials } = useGLTF('/3d_models/maze.glb') as unknown as GLTFResult
  
  // Track scroll position
  const { scrollYProgress: globalScroll } = useScroll()
  const activeScroll = scrollProgress || globalScroll
  
  // Map scroll progress to a dissolve value
  // -0.2 = fully solid, 1.2 = fully dissolved
  // Sticky lock happens at 0.29 (100vh / 350vh), so we start burning EXACTLY at 0.29
  const dissolveValue = useTransform(activeScroll, [0, 0.29, 0.70, 1], [-0.2, -0.2, 1.2, 1.2])

  const dissolveMaterial = useMemo(() => {
    const mat = materials.Material.clone()
    mat.transparent = true
    mat.side = THREE.DoubleSide // Ensure inside walls render during dissolve
    
    // Premium Tech Aesthetic
    mat.color = new THREE.Color("#475569") // Slate-600 for a visible, cool tech gray
    mat.roughness = 0.4 // Diffuse the light nicely
    mat.metalness = 0.1 // VERY low metalness so it doesn't reflect the pure black void
    
    mat.onBeforeCompile = (shader) => {
      shader.uniforms.uDissolve = { value: 0 }
      mat.userData.shader = shader
      
      shader.vertexShader = shader.vertexShader.replace(
        `#include <common>`,
        `#include <common>
         varying vec3 vWorldPos;
         varying vec3 vWorldNormal;`
      ).replace(
        `#include <worldpos_vertex>`,
        `#include <worldpos_vertex>
         vWorldPos = (modelMatrix * vec4(position, 1.0)).xyz;
         vWorldNormal = normalize((modelMatrix * vec4(objectNormal, 0.0)).xyz);`
      )

      shader.fragmentShader = shader.fragmentShader.replace(
        `#include <common>`,
        `#include <common>
         uniform float uDissolve;
         varying vec3 vWorldPos;
         varying vec3 vWorldNormal;
         
         float getBrickPattern(vec3 wPos, vec3 wNormal) {
             vec3 n = abs(wNormal);
             vec2 uv = vec2(0.0);
             if (n.x > n.y && n.x > n.z) {
                 uv = wPos.zy;
             } else if (n.z > n.x && n.z > n.y) {
                 uv = wPos.xy;
             } else {
                 uv = wPos.xz; // Floor/Ceiling
             }
             
             // Scale of the bricks
             vec2 brickSize = vec2(0.8, 0.4); 
             vec2 position = uv / brickSize;
             
             // Offset every other row
             if (fract(position.y * 0.5) > 0.5) {
                 position.x += 0.5;
             }
             
             vec2 brick = fract(position);
             vec2 useBrick = 1.0 - step(vec2(0.95, 0.90), brick); 
             float mask = useBrick.x * useBrick.y;
             
             // Add random shading variation per brick
             float randomShade = 0.75 + 0.25 * fract(sin(dot(floor(position) + vec2(0.1), vec2(12.9898, 78.233))) * 43758.5453);
             return mask * randomShade;
         }
         
         // Simplex 3D Noise
         vec3 mod289(vec3 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
         vec4 mod289(vec4 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
         vec4 permute(vec4 x) { return mod289(((x*34.0)+1.0)*x); }
         vec4 taylorInvSqrt(vec4 r) { return 1.79284291400159 - 0.85373472095314 * r; }
         float snoise(vec3 v) {
            const vec2  C = vec2(1.0/6.0, 1.0/3.0) ;
            const vec4  D = vec4(0.0, 0.5, 1.0, 2.0);
            vec3 i  = floor(v + dot(v, C.yyy) );
            vec3 x0 = v - i + dot(i, C.xxx) ;
            vec3 g = step(x0.yzx, x0.xyz);
            vec3 l = 1.0 - g;
            vec3 i1 = min( g.xyz, l.zxy );
            vec3 i2 = max( g.xyz, l.zxy );
            vec3 x1 = x0 - i1 + C.xxx;
            vec3 x2 = x0 - i2 + C.yyy;
            vec3 x3 = x0 - D.yyy;
            i = mod289(i);
            vec4 p = permute( permute( permute(
                       i.z + vec4(0.0, i1.z, i2.z, 1.0 ))
                     + i.y + vec4(0.0, i1.y, i2.y, 1.0 ))
                     + i.x + vec4(0.0, i1.x, i2.x, 1.0 ));
            float n_ = 0.142857142857; // 1.0/7.0
            vec3  ns = n_ * D.wyz - D.xzx;
            vec4 j = p - 49.0 * floor(p * ns.z * ns.z);
            vec4 x_ = floor(j * ns.z);
            vec4 y_ = floor(j - 7.0 * x_ );
            vec4 x = x_ *ns.x + ns.yyyy;
            vec4 y = y_ *ns.x + ns.yyyy;
            vec4 h = 1.0 - abs(x) - abs(y);
            vec4 b0 = vec4( x.xy, y.xy );
            vec4 b1 = vec4( x.zw, y.zw );
            vec4 s0 = floor(b0)*2.0 + 1.0;
            vec4 s1 = floor(b1)*2.0 + 1.0;
            vec4 sh = -step(h, vec4(0.0));
            vec4 a0 = b0.xzyw + s0.xzyw*sh.xxyy ;
            vec4 a1 = b1.xzyw + s1.xzyw*sh.zzww ;
            vec3 p0 = vec3(a0.xy,h.x);
            vec3 p1 = vec3(a0.zw,h.y);
            vec3 p2 = vec3(a1.xy,h.z);
            vec3 p3 = vec3(a1.zw,h.w);
            vec4 norm = taylorInvSqrt(vec4(dot(p0,p0), dot(p1,p1), dot(p2, p2), dot(p3,p3)));
            p0 *= norm.x;
            p1 *= norm.y;
            p2 *= norm.z;
            p3 *= norm.w;
            vec4 m = max(0.6 - vec4(dot(x0,x0), dot(x1,x1), dot(x2,x2), dot(x3,x3)), 0.0);
            m = m * m;
            return 42.0 * dot( m*m, vec4( dot(p0,x0), dot(p1,x1), dot(p2,x2), dot(p3,x3) ) );
         }`
      ).replace(
        `#include <roughnessmap_fragment>`,
        `#include <roughnessmap_fragment>
         float brickValue = getBrickPattern(vWorldPos, vWorldNormal);
         vec3 mortarColor = diffuseColor.rgb * 0.15;
         
         float isBrick = step(0.1, brickValue); 
         vec3 finalBrickColor = diffuseColor.rgb * brickValue; 
         
         diffuseColor.rgb = mix(mortarColor, finalBrickColor, isBrick);
         roughnessFactor = mix(0.9, 0.4, isBrick);`
      ).replace(
        `#include <dithering_fragment>`,
        `#include <dithering_fragment>
         float noise = snoise(vWorldPos * 1.5); // Density of the noise
         noise = noise * 0.5 + 0.5; // Map to 0-1
         
         if (noise < uDissolve) {
           discard;
         }
         
         // Glowing magenta edge
         if (noise < uDissolve + 0.06) {
           gl_FragColor = vec4(1.0, 0.0, 1.0, 1.0); // Neon Magenta
         }`
      )
    }
    return mat
  }, [materials.Material])

  useFrame((state) => {
    const scroll = activeScroll.get();

    // 1. Camera Fly-In (Enter the Maze)
    // Map scroll 0.0 -> 0.29 to fly from outside the maze down into the corridors
    // This perfectly matches the 100vh of scrolling it takes to lock the sticky section
    let camZ = 7;
    let camY = -0.2;
    
    if (scroll < 0.29) {
      const progress = scroll / 0.29;
      // Smooth cubic ease out
      const easeOut = 1 - Math.pow(1 - progress, 3);
      camZ = 40 - (33 * easeOut); // starts at Z=40, ends at Z=7
      camY = 15 - (15.2 * easeOut); // starts at Y=15, ends at Y=-0.2
      
      state.camera.lookAt(0, -0.2, 0);
    }
    
    // Apply position
    state.camera.position.z = camZ;
    state.camera.position.y = camY;

    // 2. Dissolve Shader Update
    if (dissolveMaterial.userData.shader) {
      dissolveMaterial.userData.shader.uniforms.uDissolve.value = dissolveValue.get();
    }
  })

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Maze_Material_0.geometry} material={dissolveMaterial} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d_models/maze.glb')
