/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_models/maze_bank_tower_by_josh_shargo.glb -o src/components/MazeBankTowerModel.tsx 
Author: jshargo (https://sketchfab.com/jshargo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/maze-bank-tower-by-josh-shargo-65972f0e72844682b0f519a3bd541ab8
Title: Maze Bank Tower by Josh Shargo
*/

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGLTF, Edges } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

// ... existing types ...
type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
  }
  materials: any
  animations: any[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/3d_models/maze_bank_tower_by_josh_shargo.glb') as unknown as GLTFResult

  // Create a deep navy glass core material
  const coreMaterial = useMemo(() => new THREE.MeshPhysicalMaterial({
    color: '#020813',
    metalness: 0.8,
    roughness: 0.2,
    transparent: true,
    opacity: 0.85,
    envMapIntensity: 1.0,
  }), []);

  // Helper function to render a mesh with a neon edge overlay
  const renderArchitecturalMesh = (geometry: THREE.BufferGeometry) => (
    <mesh geometry={geometry} material={coreMaterial}>
      {/* Edges draws bright cyan lines on the sharp angles of the geometry */}
      <Edges threshold={15} color="#EF4444" />
    </mesh>
  );

  return (
    <group {...props} dispose={null}>
      {/* Hologram Projection Base */}
      <group position={[0, -0.075, 0]}>
        {/* Glowing Rings */}
        <mesh rotation={[-Math.PI / 2, 0, 0]}>
          <ringGeometry args={[0.035, 0.045, 64]} />
          <meshBasicMaterial color="#EF4444" transparent opacity={0.8} blending={THREE.AdditiveBlending} depthWrite={false} />
        </mesh>
        <mesh rotation={[-Math.PI / 2, 0, 0]}>
          <ringGeometry args={[0.05, 0.052, 64]} />
          <meshBasicMaterial color="#EF4444" transparent opacity={0.4} blending={THREE.AdditiveBlending} depthWrite={false} />
        </mesh>
        {/* Soft core glow */}
        <mesh rotation={[-Math.PI / 2, 0, 0]}>
          <circleGeometry args={[0.035, 64]} />
          <meshBasicMaterial color="#EF4444" transparent opacity={0.2} blending={THREE.AdditiveBlending} depthWrite={false} />
        </mesh>
        
        {/* Hologram Light Beams (Shooting Upwards) */}
        <mesh position={[0, 0.1, 0]}>
          <cylinderGeometry args={[0.045, 0.045, 0.2, 32, 1, true]} />
          <meshBasicMaterial color="#EF4444" transparent opacity={0.08} blending={THREE.AdditiveBlending} depthWrite={false} side={THREE.DoubleSide} />
        </mesh>
      </group>

      {/* Upward Holographic Lights */}
      <pointLight position={[0, -0.1, 0]} color="#EF4444" intensity={5} distance={1} />
      
      <group position={[0, -0.074, 0]} rotation={[-Math.PI, Math.PI / 2, 0]}>
        {renderArchitecturalMesh(nodes.Object_2.geometry)}
        {renderArchitecturalMesh(nodes.Object_3.geometry)}
        {renderArchitecturalMesh(nodes.Object_4.geometry)}
        {renderArchitecturalMesh(nodes.Object_5.geometry)}
        {renderArchitecturalMesh(nodes.Object_6.geometry)}
        {renderArchitecturalMesh(nodes.Object_7.geometry)}
        {renderArchitecturalMesh(nodes.Object_8.geometry)}
        {renderArchitecturalMesh(nodes.Object_9.geometry)}
        {renderArchitecturalMesh(nodes.Object_10.geometry)}
        {renderArchitecturalMesh(nodes.Object_11.geometry)}
        {renderArchitecturalMesh(nodes.Object_12.geometry)}
        {renderArchitecturalMesh(nodes.Object_13.geometry)}
        {renderArchitecturalMesh(nodes.Object_14.geometry)}
        {renderArchitecturalMesh(nodes.Object_15.geometry)}
      </group>
    </group>
  )
}

useGLTF.preload('/3d_models/maze_bank_tower_by_josh_shargo.glb')
