/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_models/money_palm_tree.glb -o src/components/MoneyPalmTreeModel.tsx 
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    palm: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d_models/money_palm_tree.glb') as unknown as GLTFResult

  useEffect(() => {
    if (materials.material) {
      // Fix blown-out lighting by adjusting physical material properties
      materials.material.metalness = 0.0;
      materials.material.roughness = 1.0;
      materials.material.envMapIntensity = 0;
      materials.material.emissive = new THREE.Color('#000000');
      
      // Fix washed-out texture colors by enforcing sRGB color space
      if (materials.material.map) {
        materials.material.map.colorSpace = THREE.SRGBColorSpace;
        materials.material.map.needsUpdate = true;
      }
      
      // Reset color multiplier to full white so the texture is fully bright again
      materials.material.color = new THREE.Color('#ffffff');
      
      materials.material.needsUpdate = true;
      
      // Make material double sided so falling leaves look good from both sides
      materials.material.side = THREE.DoubleSide;

      // Slice off the round sandy base at the bottom of the tree
      materials.material.clippingPlanes = [new THREE.Plane(new THREE.Vector3(0, 1, 0), 1.5)];
      materials.material.clipShadows = true;
    }
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.palm.geometry} material={materials.material} />
    </group>
  )
}

useGLTF.preload('/3d_models/money_palm_tree.glb')
