/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_models/one_chase_manhattan_bank.glb -o src/components/OneChaseManhattanBankModel.tsx 
Author: NanoRay (https://sketchfab.com/NanoRay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/one-chase-manhattan-bank-fdadc3b019524eed92db2274434a7785
Title: One Chase Manhattan Bank
*/

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGLTF, Edges } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
  }
  materials: {
    color_10988977: THREE.MeshStandardMaterial
    color_11316396: THREE.MeshStandardMaterial
    color_12500670: THREE.MeshStandardMaterial
    color_12568524: THREE.MeshStandardMaterial
    color_13157565: THREE.MeshStandardMaterial
    color_13291736: THREE.MeshStandardMaterial
    color_14408925: THREE.MeshStandardMaterial
    color_14541540: THREE.MeshStandardMaterial
    color_14867667: THREE.MeshStandardMaterial
    color_14999512: THREE.MeshStandardMaterial
    color_16777215: THREE.MeshStandardMaterial
    color_1991424: THREE.MeshStandardMaterial
    color_2501421: THREE.MeshStandardMaterial
    color_25360: THREE.MeshStandardMaterial
    color_2829873: THREE.MeshStandardMaterial
    color_3513670: THREE.MeshStandardMaterial
    color_4028998: THREE.MeshStandardMaterial
    color_4030347: THREE.MeshStandardMaterial
    color_4695479: THREE.MeshStandardMaterial
    color_4751056: THREE.MeshStandardMaterial
    color_5328973: THREE.MeshStandardMaterial
    color_9010010: THREE.MeshStandardMaterial
    color_9012867: THREE.MeshStandardMaterial
    color_9997435: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d_models/one_chase_manhattan_bank.glb') as unknown as GLTFResult
  const renderArchitecturalMesh = (geometry: THREE.BufferGeometry, material: THREE.Material) => (
    <mesh geometry={geometry} material={material}>
      <Edges threshold={15} color="#EF4444" opacity={0.5} transparent />
    </mesh>
  );

  return (
    <group {...props} dispose={null}>

      <group position={[0, -100.818, 53.182]} rotation={[-Math.PI, 0, 0]}>
        {renderArchitecturalMesh(nodes.Object_2.geometry, materials.color_10988977)}
        {renderArchitecturalMesh(nodes.Object_3.geometry, materials.color_11316396)}
        {renderArchitecturalMesh(nodes.Object_4.geometry, materials.color_12500670)}
        {renderArchitecturalMesh(nodes.Object_5.geometry, materials.color_12568524)}
        {renderArchitecturalMesh(nodes.Object_6.geometry, materials.color_12568524)}
        {renderArchitecturalMesh(nodes.Object_7.geometry, materials.color_13157565)}
        {renderArchitecturalMesh(nodes.Object_8.geometry, materials.color_13291736)}
        {renderArchitecturalMesh(nodes.Object_9.geometry, materials.color_14408925)}
        {renderArchitecturalMesh(nodes.Object_10.geometry, materials.color_14541540)}
        {renderArchitecturalMesh(nodes.Object_11.geometry, materials.color_14867667)}
        {renderArchitecturalMesh(nodes.Object_12.geometry, materials.color_14999512)}
        {renderArchitecturalMesh(nodes.Object_13.geometry, materials.color_16777215)}
        {renderArchitecturalMesh(nodes.Object_14.geometry, materials.color_1991424)}
        {renderArchitecturalMesh(nodes.Object_15.geometry, materials.color_2501421)}
        {renderArchitecturalMesh(nodes.Object_16.geometry, materials.color_25360)}
        {renderArchitecturalMesh(nodes.Object_17.geometry, materials.color_2829873)}
        {renderArchitecturalMesh(nodes.Object_18.geometry, materials.color_3513670)}
        {renderArchitecturalMesh(nodes.Object_19.geometry, materials.color_4028998)}
        {renderArchitecturalMesh(nodes.Object_20.geometry, materials.color_4030347)}
        {renderArchitecturalMesh(nodes.Object_21.geometry, materials.color_4695479)}
        {renderArchitecturalMesh(nodes.Object_22.geometry, materials.color_4751056)}
        {renderArchitecturalMesh(nodes.Object_23.geometry, materials.color_5328973)}
        {renderArchitecturalMesh(nodes.Object_24.geometry, materials.color_9010010)}
        {renderArchitecturalMesh(nodes.Object_25.geometry, materials.color_9012867)}
        {renderArchitecturalMesh(nodes.Object_26.geometry, materials.color_9997435)}
      </group>
    </group>
  )
}

useGLTF.preload('/3d_models/one_chase_manhattan_bank.glb')
