/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_models/vintage_clock_model.glb -o src/components/VintageClockModel.tsx -t 
Author: Marie (https://sketchfab.com/Polairee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-clock-2062961986804f5d8154703e32cba6c8
Title: Vintage clock
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_56: THREE.Mesh
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_34: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_48: THREE.Mesh
    Object_54: THREE.Mesh
  }
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d_models/vintage_clock_model.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    if (actions['Animation']) {
      actions['Animation'].setLoop(THREE.LoopRepeat, Infinity)
      actions['Animation'].play()
    }

    // Tint the clock materials to match the orange theme
    const darkOrange = new THREE.Color('#C2410C');
    const mainOrange = new THREE.Color('#F97316');
    const lightOrange = new THREE.Color('#FDBA74');

    Object.entries(materials).forEach(([key, material]) => {
      // Material.004 is used for the inner gears
      // Material.005 is used for the hands
      // Material.002/003 are the outer casing
      if (key === 'Material.004') {
        material.color.set(mainOrange);
      } else if (key === 'Material.005') {
        material.color.set(lightOrange);
      } else {
        material.color.set(darkOrange);
      }
    });
  }, [actions, materials])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cylinder007_13" position={[-0.001, 0.055, 0.006]} rotation={[0, 0.001, 0]} scale={[0.166, 0.003, 0.166]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder006_14" position={[-0.431, 0.057, 0.448]} rotation={[0, 0.001, 0]} scale={[0.138, 0.003, 0.138]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder008_16" position={[0.155, 0.009, -0.087]} rotation={[0, 0.001, 0]} scale={[0.1, 0.002, 0.1]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder009_17" position={[0.256, 0.006, 0.255]} rotation={[0, -1.134, 0]} scale={[0.052, 0.002, 0.062]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder012_20" position={[-0.557, 0.035, -0.279]} rotation={[0, 0.001, 0]} scale={[0.138, 0.003, 0.138]}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder013_21" position={[-0.435, 0.006, 0.067]} rotation={[0, -1.134, 0]} scale={[0.052, 0.002, 0.062]}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder015_23" position={[0.152, 0.006, -0.411]} rotation={[0, -1.134, 0]} scale={[0.052, 0.002, 0.062]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder016_24" position={[0.466, -0.017, 0.037]} rotation={[0, -1.135, 0]} scale={[0.052, 0.002, 0.062]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cube002_26" position={[-0.001, -0.004, 0.006]} rotation={[Math.PI, -1.474, Math.PI]} scale={[0.466, 0.002, 0.002]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials['Material.005']} />
              </group>
              <group name="Cylinder_0" scale={[1, 0.087, 1]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
              </group>
              <group name="Cylinder001_1" position={[1.054, 0, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.076, -0.076, -0.092]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
              </group>
              <group name="Cylinder002_2" position={[1.261, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.075, 0.129, 0.075]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.002']} />
              </group>
              <group name="Cylinder003_3" scale={[1, 0.087, 1]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.003']} />
              </group>
              <group name="Cylinder004_4" position={[1.26, 0, -0.14]} rotation={[-Math.PI / 2, -0.693, -Math.PI]} scale={[0.042, 0.016, 0.051]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.002']} />
              </group>
              <group name="Cube112_5" rotation={[0, 0.061, 0]} scale={[0.032, 0.012, 0.009]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material.006']} />
              </group>
              <group name="Cube001_6" position={[0, 0.015, 0]} rotation={[0, 0.061, 0]} scale={[0.022, 0.009, 0.006]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material_0} />
              </group>
              <group name="Cube004_7" position={[0.718, 0.082, -0.078]} rotation={[-3.135, 0.332, -3.133]} scale={[-0.077, -0.012, -0.013]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.006']} />
              </group>
              <group name="Cube011_8" position={[0, -0.015, 0]} rotation={[0.017, 0.385, 0.016]} scale={[-0.077, -0.012, -0.013]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['Material.006']} />
              </group>
              <group name="Cube015_9" position={[-0.724, 0.018, 0.059]} rotation={[-3.107, -0.336, 3.07]} scale={[-0.077, -0.012, -0.013]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.material_0} />
              </group>
              <group name="Cylinder005_10" position={[-0.001, 0.034, 0.006]} scale={[0.016, 0.103, 0.016]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Material.005']} />
              </group>
              <group name="Cube030_11" position={[-0.331, 0.113, 0.006]} scale={[0.456, 0.002, 0.007]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['Material.005']} />
              </group>
              <group name="Cube031_12" position={[-0.001, -0.004, 0.006]} rotation={[0, -0.435, 0]} scale={[0.335, 0.002, 0.005]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Material.005']} />
              </group>
              <group name="Cube032_15" position={[0.135, -0.026, 0.137]} rotation={[0, -1.234, 0]} scale={[-2.981, -0.005, -2.484]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder010_18" position={[0.158, -0.018, -0.089]} scale={[0.042, 0.034, 0.042]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder011_19" position={[0.259, -0.018, 0.253]} scale={[0.042, 0.035, 0.042]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder014_22" position={[0.153, -0.018, -0.418]} scale={[0.042, 0.027, 0.042]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder017_25" scale={[1, 0.087, 1]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['Material.003']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d_models/vintage_clock_model.glb')
